# Dan Muir's Resume - 2021

[config]
github_source = "https://github.com/dmmuir/resume/tree/main"
pdf_file = "https://github.com/dmmuir/resume/raw/gh-pages/dmuir-resume.pdf"

[basics]
name = "Daniel Muir"
label = "Software Engineer"
picture = ""
summary = "Software Engineer, passionate about simplifying systems. 10 years of experience in engineering."
phone = ""
email = "daniel.muir.14@gmail.com"

[basics.location]
city = "Downingtown, PA USA"
timezone = "Eastern Standard (EST)"


[[basics.profiles]]
network = "Github"
username = "dmmuir"
url = "https://github.com/dmmuir"

[[basics.profiles]]
network = "Linkedin"
username = "danmuir"
url = "https://www.linkedin.com/in/danmuir/"


[[skills]]
name = "Programming"
keywords = ["Rust", "Javascript", "Shell", "Python", "HTML5", "AWK", "SQL", "Java"]

[[skills]]
name = "Technologies"
keywords = ["Git", "Linux", "Docker", "Kubernetes", "React", "Spinnaker", "Vim"]

[[skills]]
name = "Paradigms"
keywords = ["Functional", "Data Oriented", "First Principles"]


[languages]
language = "English"
fluency = "Native speaker"


[[work]]
company = "Cerner Corporation"
website = "https://www.cerner.com/"
logo = ""
duration = "3 yrs"
highlights = [
"Medicare regulation analysis with Natural Language processing in Rust and Python",
"Dignostic Related Grouping service migration to cloud architecture",
"Cloud deployment strategy and orchastration with Kubernetes and Spinnaker"
]

[[work.roles]]
position = "Software Engineer II"
date = "Sep 2019 - Present"
summary = "Engineer in healthcare financial systems with a focus in contracts and reimbursement."

[[work.roles]]
position = "Software Engineer I"
date = "Sep 2018 - Sep 2019"
summary = "Fullstack engineer managing my team's cloud deployment strategy and infrastructure."


[[work]]
company = "Tx3 Services LLC"
website = "https://www.tx3services.com/"
logo = ""
duration = "2 yrs 6 mos"

[[work.roles]]
position = "Associate Systems Engineer"
date = "Jan 2018 - Sep 2018"
summary = "Lead validation systems development, implementation, and product installation. Focus in client facing DevOps collaboration."

[[work.roles]]
position = "Associate Quality Engineer"
date = "Apr 2016 - Jan 2018"
summary = "Automated gui testing for Life Science systems validation."


[[work]]
company = "ONExia Inc"
website = "http://onexia.com/"
logo = ""
duration = "5 yrs 8 mos"

[[work.roles]]
position = "Mechanical Engineering Intern"
date = "Jun 2015 - Mar 2016"
summary = "Engineering internship in process and quality assurance development for manufacturing equipment, and engineering assistance in machine design, detail design, documentation, and testing."

[[work.roles]]
position = "Engineering Technician"
date = "Aug 2010 - Mar 2013"
summary = "Engineering technician position tasked with machine part fabrication and product assembly."


[[work]]
company = "DML Automotive"
logo = ""
duration = "1 yr 4 mos"

[[work.roles]]
position = "Shop Attendant"
date = "May 2009 - Aug 2010"
summary = "Highschool job, duties included shop maintenance, cleaning, part and vehicle delivery and pick up."


[[education]]
institution = "Delaware County Community College"
area = "Engineering (focus in mechanics)"
studyType = "Associate"
date = "2015 - 2016"


[[volunteer]]
organization = "Covenant Fellowship Church"
position = "Audio Engineer"
date = "Sep 2006 - Present"
duration = "15 yrs"
summary = "Co-lead a team of volunteers to steward and run the audio production equipment for Sunday morning services."


[interests]
keywords = [
	"Software Automation",
	"Audio Engineering",
	"Food. Coffee. Beer.",
	"Traveling",
	"Internet Performance",
	"Data Compression Formats",
]

[learning]
keywords = ["Bass Guitar", "Data Compression", "Grilling/Smoking Meats"]
