name: "Publish to GH-Pages"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Setup Git
      run : |
        git config --global user.name "dmmuir"
        git config --global user.email "dmmuir@users.noreploy.github.com"
        git remote set-url origin https://x-oauth-basic:${{ secrets.ACCESS_TOKEN }}@github.com/dmmuir/resume.git
        git fetch origin gh-pages
    - name: Install 
      run: |
        cargo install --git https://github.com/gnprice/toml-cli.git
        cd ./themes/jsonresume-theme-flat && npm install ; cd -
    - name: Build
      run: toml get resume.toml . | node themes/jsonresume-theme-flat/index.js > ./resume.html
    - name: Publish
      run: |
        git checkout gh-pages
        mv resume.html index.html
        git add index.html
        git commit -m "Update resume"
        git push

